name: uarray
channels:
  - pytorch
  - conda-forge
dependencies:
  - python <3.9
  - pip
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - mypy
  - pytorch-cpu
  - scipy
  - dask
  - sparse
  - doc8
  - black
  - pytest-mypy
  - pytest-black
